### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by Zulu-Inuoe** [Virtual-Insurance-Products/clim-web-demo#1]
Could you please add a license to this project? I'm interested in setting up Github Pages with this demo so that people can try the demo online (without downloading,  configuring, & building), but I'd want a license to be added first. 

Thanks!

**Comment by ppymdjr** [comment]
I probably need to add licenses to a few of the repos here. I’ve put the MIT license for this one. Hope that’s ok - let me know if not. 

Glad someone is interested in it :)
